name: example
description: A web server built using the orbit package.
version: 1.0.0
publish_to: "none"
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  shelf: ^1.1.0
  shelf_router: ^1.1.1
  orbit:
    path: ../

dev_dependencies:
  pedantic: ^1.10.0
