name: orbit
description: A Dart backend we have always wanted.
version: 0.0.1
# homepage: https://www.example.com
environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.16.0

dependencies:
  collection: ^1.15.0
  dart_jsonwebtoken: ^2.3.2
  get_it: ^7.2.0
  http_parser: ^4.0.0
  path: ^1.8.0
  pedantic: ^1.10.0
  postgres: ^2.3.2
  recase: ^4.0.0
  shelf: ^1.2.0
  shelf_router: ^1.1.1
